services:
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_PLUGIN=true
      - plugins.security.ssl.http.enabled=false
      - plugins.security.allow_default_init_securityindex=true
      - plugins.security.check_snapshot_restore_write_privileges=false
      - plugins.security.restapi.roles_enabled=[]
      - node.max_local_storage_nodes=1
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.0
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - 'DISABLE_SECURITY_DASHBOARDS_PLUGIN=true'
      - 'OPENSEARCH_SECURITY_ENABLED=false'
      - 'OPENSEARCH_USERNAME=admin'
      - 'OPENSEARCH_PASSWORD=admin'
    networks:
      - opensearch-net
    depends_on:
      opensearch:
        condition: service_healthy

networks:
  opensearch-net:
    name: pqctlog-opensearch-net
    driver: bridge

volumes:
  opensearch-data:
    name: pqctlog-opensearch-data
