# OpenSearch Configuration
opensearch:
  host: "localhost"
  port: 9200
  use_ssl: false
  verify_certs: false
  timeout: 30
  max_retries: 3
  http_auth:
    username: "admin"
    password: "admin"
  index_prefix: "pqctlog_"

# Scanner Configuration
scanner:
  max_entries: 1000
  scan_interval: 3600
  worker_threads: 5

# TLS Scanner Configuration
tls_scanner:
  enabled: true
  timeout: 10
  max_workers: 10
  scan_interval: 86400
  ports: [443, 8443]
  tls_versions:
    - "TLSv1.3"
    - "TLSv1.2"
    - "TLSv1.1"
    - "TLSv1.0"
  ciphersuites:
    # Modern TLS 1.3 ciphers
    - "TLS_AES_128_GCM_SHA256"
    - "TLS_AES_256_GCM_SHA384"
    - "TLS_CHACHA20_POLY1305_SHA256"
    # ECDHE ciphers (TLS 1.2)
    - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
    - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
    - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
    - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
    - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256"
    - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256"
  post_quantum_ciphers:
    # NIST standardized algorithms (highest priority)
    - "MLKEM"      # ML-KEM (standardized Kyber)
    - "MLDSA"      # ML-DSA (standardized Dilithium)  
    - "SLHDSA"     # SLH-DSA (standardized SPHINCS+)
    # Legacy/experimental names
    - "KYBER"
    - "FALCON"
    - "DILITHIUM"
    - "SPHINCS"
    - "NTRU"
    - "FRODO"
    - "SABER"
  # Enable external PQ testing tools
  enable_pq_testing: true
  pq_test_timeout: 15
    - "MLKEM"
    - "MLDSA"

# Logging Configuration
logging:
  level: "INFO"
  max_size: 10485760
  backup_count: 5
