# OpenSearch configuration
opensearch:
  host: "localhost"  # Using localhost for direct connection
  port: 9200
  use_ssl: false
  verify_certs: false
  http_auth:
    username: "admin"
    password: "admin"
  index_prefix: "pqctlog_"

# CT Log configuration
ct_logs:
  - url: "https://ct.googleapis.com/logs/argon2023"
    name: "Google Argon2023"
    description: "Google's 2023 Certificate Transparency log"
  - url: "https://ct.cloudflare.com/logs/nimbus2023"
    name: "Cloudflare Nimbus2023"
    description: "Cloudflare's 2023 Certificate Transparency log"

# Scanner configuration
scanner:
  timeout: 10  # seconds
  max_retries: 3
  concurrency: 10
  user_agent: "pqCTLOG/1.0"

# Logging configuration
logging:
  level: "INFO"
  file: "pqctlog.log"
  max_size: 10485760  # 10MB
  backup_count: 5
